version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: builder
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always