# name: Deploy to AWS
# on:
#   push:
#     branches:
#       - "main"
# env:
#   AWS_REGION: ap-southeast-1
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
#   SERVER_PUBLIC_IP: ${{ secrets.AWS_PUBLIC_KEY }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4  
#       - name: Deploy docker image to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ env.SERVER_PUBLIC_IP }}
#           username: ubuntu
#           key: ${{ env.PRIVATE_SSH_KEY }}
#           envs: PRIVATE_SSH_KEY,REGISTRY,REPOSITORY,IMAGE_TAG,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION,AWS_REGION
#           script: |-
#             cd /var/www/tool-neobrutalism-ui
#             sudo git pull
            